version: 1.0.{build}

environment:
  matrix:
    - generator: "MinGW Makefiles"
    - generator: "Visual Studio 12"

install:
  - cinst biicode mingw
  - cmd: set PATH=%PATH:CMake 2.8\bin=%;C:\ProgramData\chocolatey\lib\cmake.3.0.2\content\cmake-3.0.2-win32-x86\bin
  - cmd: set PATH=%PATH:Git\bin=%;C:\MinGW\bin
  - cmd: set PATH=%PATH%;C:\Program Files (x86)\BiiCode\bii;  
  - cmd: set PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\; #ml for MinGW build
  - cmd: cmake --version
  - cmd: g++ --version
  - cmd: bii --version

before_build:
  - cmd: bii init -L
  - cmd: bii configure -G "%generator%"

build_script:
  - cmd: bii build

test_script:
  - cmd: bin\amalulla_unit_test_main.exe --reporter=info


